### PR TITLE
New Red Hat One theme

### PR DESCRIPTION
**Pull request by tonykay**
Uses the new theme just released

### CODE REVIEW

**Comment by erwangranger** [comment]
Hi Tony. 
Could you possibly restart from the `dev` branch, and merge back against it. You started from `main`, which was weeks old. 
thanks.

**Comment by tonykay** [comment]
> Hi Tony. Could you possibly restart from the `dev` branch, and merge back against it. You started from `main`, which was weeks old. thanks.

Sure

**Comment by guimou** [comment]
@tonykay I just did some alignements bewteen dev and main. So you would want to update your dev branch and rebase your changes from there.

**Comment by erwangranger** [comment]
I'm closing this PR for now. I suggest a new PR targeting the `dev` branch properly.

**Pull request closed without merging**
