### PR TITLE
minor fixes and update images

### PR DESCRIPTION
**Pull request by rcarrata**
minor fixes and update images of RHOAI 2.8

### CODE REVIEW

**Comment by rcarrata** [comment]
@erwangranger @guimou this PR solves some of the issues in https://github.com/rh-aiservices-bu/insurance-claim-processing/issues/163  

Can we double check that the Deploy of the Model in lab4 is using the Multi-Model serving platform?

**Comment by erwangranger** [comment]
Currently, it does. We can look at using Single-Model serving instead in the example, but it feels less urgent than other changes. Multi-Model is fine for now IMO, but we can discuss.

**Comment by rcarrata** [comment]
due this only applies to the RHOAI 2.8, should be wait until we moved the lab to this version and only fix the minor typos, not updating the images for RHOAI 2.8 in the lab? what do you think @erwangranger @guimou ?

**Comment by guimou** [comment]
Merging as the Lab now runs on RHOAI 2.8

**Pull request merged**
